/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2019-08-09 02:23:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DetailBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
 String id = (String)session.getAttribute("id"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->\r\n");
      out.write("    <title>클라우스</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"/resources/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- 메인css -->\r\n");
      out.write("    <link href=\"/resources/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->\r\n");
      out.write("    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" <script>\r\n");
      out.write("  \r\n");
      out.write(" var id =\"");
      out.print(id);
      out.write("\";\r\n");
      out.write(" id = id.trim();\r\n");
      out.write("   \r\n");
      out.write(" </script>\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"padding-top:60px; background-color:#2c3338;\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/navi.jsp", out, false);
      out.write(" <!-- 상단바 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("<div class=\"row\">\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-6\">\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"box box-primary\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"box-header\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form role=\"form\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type='hidden' name='bno' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type='hidden' name='page' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pagecri.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type='hidden' name='perPageNum' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pagecri.perPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type='hidden' name='searchType' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pagecri.searchType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type='hidden' name='keyword' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pagecri.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleInputEmail1\">Title</label> <input type=\"text\" name='title' \r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleInputPassword1\">Content</label>\r\n");
      out.write("\t\t\t\t\t<textarea class=\"form-control\" name=\"content\" rows=\"3\"\treadonly=\"readonly\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"box-footer\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class = \"col-md-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class = \"col-md-3\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-warning\">Modify</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class = \"col-md-3\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-danger\">REMOVE</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class = \"col-md-3\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">LIST ALL</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\"></div>\t\t\r\n");
      out.write("</div> \r\n");
      out.write("\t\t<!--/.col (left) -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class = \"row\" id=\"replylist\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class= \"row\" id=\"pageing\">\t</div> <!-- 페이징 들어갈곳 -->\t\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row\">   <!-- 댓글처리 시작 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-6\" style=\"background:#5D5D5D;\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"box box-success\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"box-header\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleInputEmail1\">ReplyText</label> \r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" type=\"text\" placeholder=\"REPLY TEXT\" id=\"newReplyText\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"box-footer\" style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn\" id=\"replyinsert\" style=\"background:#FAED7D;color:blue;\">댓글 등록</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-3\"></div>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<br><br><br> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 스크립트 선언부 -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\treplylist(1);\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar formObj = $(\"form[role='form']\");\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log(formObj);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".btn-warning\").on(\"click\", function(){\r\n");
      out.write("\t\tformObj.attr(\"action\", \"/modify\");\r\n");
      out.write("\t\tformObj.attr(\"method\", \"get\");\t\t\r\n");
      out.write("\t\tformObj.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".btn-danger\").on(\"click\", function(){\r\n");
      out.write("\t\tformObj.attr(\"action\", \"/remove\");\r\n");
      out.write("\t\tformObj.attr(\"method\", \"get\");\t\t\r\n");
      out.write("\t\tformObj.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".btn-primary\").on(\"click\", function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\tformObj.attr(\"action\", \"/board\");\r\n");
      out.write("\t\tformObj.attr(\"method\",\"get\");\r\n");
      out.write("\t\tformObj.submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("$(\"#replyinsert\").on(\"click\", function(){\t //댓글등록 ajax \r\n");
      out.write("\t\r\n");
      out.write("\t\tvar bno = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\tvar replyer = id;\r\n");
      out.write("\t\tvar replytext = $(\"#newReplyText\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  $.ajax({\r\n");
      out.write("\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\turl:'/replies/',\r\n");
      out.write("\t\t\t\theaders: { \r\n");
      out.write("\t\t\t\t      \"Content-Type\": \"application/json\",\r\n");
      out.write("\t\t\t\t      \"X-HTTP-Method-Override\": \"POST\" },\r\n");
      out.write("\t\t\t\tdataType:'text',\r\n");
      out.write("\t\t\t\tdata: JSON.stringify({bno:bno, replyer:replyer, replytext:replytext}),\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"result: \" + result);\r\n");
      out.write("\t\t\t\t\tif(result == 'SUCCESS'){\r\n");
      out.write("\t\t\t\t\t\talert(\"등록 되었습니다.\");\t\r\n");
      out.write("\t\t\t\t\t\treplylist();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("\t\r\n");
      out.write("  \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function replylist(replyPage){   //리플 목록 데이터 갱신\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\r\n");
      out.write("\t\tif(replyPage==null || replyPage==undefined || replyPage==\"null\" )\r\n");
      out.write("\t\t\treplyPage=1;\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\r\n");
      out.write("\t\t$.ajax({  \r\n");
      out.write("\t\t\t  url: '/replies/'+ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+ '/'+replyPage,\r\n");
      out.write("\t\t\t  data: \"test\",  \r\n");
      out.write("\t\t\t  success:function(data){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t  replylistimpl(data);\r\n");
      out.write("\t\t\t\t  printPaging(data.cri, $(\".pagination\"));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t},  \r\n");
      out.write("\t\t\t  dataType: \"JSON\"  \r\n");
      out.write("\t\t\t});  \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("function replylistimpl(data){   //리플 목록 화면구현\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar clickcheck = true;\r\n");
      out.write("\t\tvar list = data.list;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar replyid =\"\";\r\n");
      out.write("\t\r\n");
      out.write("\t  \r\n");
      out.write("\r\n");
      out.write("\t\tvar $replyappend = $(\"<div id='replyappend'></div>\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfor(var i = 0; i<list.length;i++){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar replyid =  list[i].replyer;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar str ='';\r\n");
      out.write("\t\t\tstr += '<div class=\"row\"><div class = \"col-md-3\"></div>';\r\n");
      out.write("\t\t\tstr += '<div class = \"col-md-6\" id=\"replymain\" style=\"border:5px solid gray;\">';\r\n");
      out.write("\t\t\tstr += '<div><br></div>';\r\n");
      out.write("\t\t\tstr += '<p align=\"left\" style=\"color:white;font-size:14px\">'+ list[i].replyer +'</p>';\r\n");
      out.write("\t\t\tstr += '<div id=\"replymaintext\" style=\"background:#F6F6F6;overflow:hidden;height:auto;\">';\r\n");
      out.write("\t\t\tstr +=  '<textarea id = \"replycontent'+ list[i].rno +'\" readonly style=\"background-color:transparent;width:100%;resize:none;\">' + list[i].replytext +'</textarea></div>';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(id==replyid){str +='<br><div style=\"float:right;\"><input type=\"button\" id=\"modi'+list[i].rno+'\"  class=\"btn\" value=\"수정\" style=\"background:#FAED7D;color:blue\" data-rno =\"'+list[i].rno+'\"> &nbsp;'\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t + '<div id=\"mod'+i+'\" style=\"float:right;\"><input type=\"button\" id=\"delete'+list[i].rno+'\"  class=\"btn\" value=\"삭제\"style=\"background:#FAED7D;color:blue;\" data-rno =\"'+list[i].rno+'\"><br><br><br></div>'\r\n");
      out.write("\t\t\t + '<input type=\"hidden\" id=\"replyrno'+list[i].rno+'\"  value = \"'+list[i].rno+'\">';}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\telse { str+='<div><br><br><br></div>';}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$replyappend.append(str);\t\r\n");
      out.write("\t\t\t$(document).on(\"click\",\"#modi\"+list[i].rno,function(){ //리플 수정\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tif(clickcheck == true)\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t{\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tvar reply = $(this);\r\n");
      out.write("\t\t\t$(\"#replycontent\"+reply.attr(\"data-rno\")).attr(\"readonly\",false);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treply.attr(\"value\",\"수정등록\");\r\n");
      out.write("\t\t\t\treply.attr(\"style\",\"background:red;\");\r\n");
      out.write("\t\t\t\treply.attr(\"style\",\"color:blue;\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\tclickcheck = false;\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\tvar reply = $(this);\t\r\n");
      out.write("\t\t  \treplymodi(reply.attr(\"data-rno\"));         \r\n");
      out.write("\t\t    clickcheck = true;\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t  \r\n");
      out.write("});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("$(document).on(\"click\",\"#delete\"+list[i].rno,function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\tvar reply = $(this);\r\n");
      out.write("\t    replydelete(reply.attr(\"data-rno\"));\t   //리플 삭제 이벤트 추가\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("\t\t$replyappend.append('<div class=\"text-center\"><ul id=\"pagination\" class=\"pagination pagination-sm no-margin \"></ul></div>')\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$(\"#replylist\").html($replyappend.html());\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction replymodi(rno){  //리플 수정\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar content = $(\"#replycontent\"+rno).val();\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  $.ajax({\r\n");
      out.write("\t\t\t\ttype:'put',\r\n");
      out.write("\t\t\t\turl:'/replies/'+rno,\r\n");
      out.write("\t\t\t\theaders: { \r\n");
      out.write("\t\t\t\t      \"Content-Type\": \"application/json\",\r\n");
      out.write("\t\t\t\t      \"X-HTTP-Method-Override\": \"PUT\" },\r\n");
      out.write("\t\t\t\tdata:JSON.stringify({replytext:content}), \r\n");
      out.write("\t\t\t\tdataType:'text', \r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"result: \" + result);\r\n");
      out.write("\t\t\t\t\tif(result == 'SUCCESS'){\r\n");
      out.write("\t\t\t\t\t\talert(\"수정 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\treplylist();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction replydelete(rno){ //리플 삭제구현\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\t\ttype:'delete',\r\n");
      out.write("\t\t\t\turl:'/replies/'+rno,\r\n");
      out.write("\t\t\t\theaders: { \r\n");
      out.write("\t\t\t\t      \"Content-Type\": \"application/json\",\r\n");
      out.write("\t\t\t\t      \"X-HTTP-Method-Override\": \"delete\" },\r\n");
      out.write("\t\t\t\tdataType:'text',\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"result: \" + result);\r\n");
      out.write("\t\t\t\t\tif(result == 'SUCCESS'){\r\n");
      out.write("\t\t\t\t\t\talert(\"삭제되었습니다.\");\t\r\n");
      out.write("\t\t\t\t\t\treplylist();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tvar printPaging = function(pageMaker, target) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar str = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tif (pageMaker.prev) {\r\n");
      out.write("\t\t\tstr += \"<li><a href='\" + (pageMaker.startPage - 1)\r\n");
      out.write("\t\t\t\t\t+ \"'> << </a></li>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfor (var i = pageMaker.startPage, len = pageMaker.endPage; i <= len; i++) {\r\n");
      out.write("\t\t\tvar strClass = pageMaker.page.page == i ? 'class=active' : '';\r\n");
      out.write("\t\t\tstr += \"<li \"+strClass+\"><a href='\"+i+\"'>\" + i + \"</a></li>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (pageMaker.next) {\r\n");
      out.write("\t\t\tstr += \"<li><a href='\" + (pageMaker.endPage + 1)\r\n");
      out.write("\t\t\t\t\t+ \"'> >> </a></li>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t  target.html(str);\r\n");
      out.write("\t  \r\n");
      out.write("\t  paginationclick();\r\n");
      out.write("\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction paginationclick(){\r\n");
      out.write("\t$(\".pagination\").on(\"click\", \"li a\", function(event){  // 리플 페이징 처리\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\tevent.preventDefault();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treplyPage = $(this).attr(\"href\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treplylist(replyPage);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\tfunction search(){\r\n");
      out.write("\r\n");
      out.write("\tvar keyword = $(\"#keyword\").val();\r\n");
      out.write("\tlocation.href= \"search?cate=all&keyword=\"+keyword;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->\r\n");
      out.write("    <script src=\"/resources/bootstrap/js/bootstrap.min.js\"></script>  \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
