/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2019-08-09 00:55:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
 String id = (String)session.getAttribute("id");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 상단바 시작 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar navbar-default navbar-fixed-top\" style=\"background-color:#2c3338;\">\r\n");
      out.write("<br>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("   \t\t<div class=\"container-fluid\">\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<div class=\"row\">\r\n");
      out.write("    \t \t<p align=\"right\" style=\"text-align: right;\">\r\n");
      out.write("    \t \t\r\n");
      out.write("     \t\t");
if("admin".equals(id)){
      out.write(" \r\n");
      out.write("     \t\t<font color=\"white\"><a href=\"memberinfo\">회원정보</a></font> &nbsp; &nbsp;  \r\n");
      out.write("     \t\t<font color=\"white\"><a href=\"orderlist\">주문내역관리</a></font> &nbsp; &nbsp;\r\n");
      out.write("     \t\t<font color=\"white\"><a href=\"upload\">상품업로드</a></font> &nbsp; &nbsp; \r\n");
      out.write("     \t\t<font color=\"white\"><a href=\"board\">문의게시판</a></font> &nbsp; &nbsp; \r\n");
      out.write("     \t\t");
} 
     		else{
      out.write("\r\n");
      out.write("     \t\t<font color=\"white\"><a href=\"mypage\">마이페이지</a></font>&nbsp; &nbsp;  \r\n");
      out.write("     \t\t<font color=\"white\"><a href=\"inorder\">주문내역</a></font> &nbsp; &nbsp;\r\n");
      out.write("     \t\t<font color=\"white\"><a href=\"cartlist\">장바구니</a></font>  &nbsp; &nbsp; \r\n");
      out.write("     \t\t<font color=\"white\"><a href=\"board\">문의게시판</a></font> &nbsp; &nbsp; \r\n");
      out.write("     \t\t");
}
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("\t \t\t");
if(id==null){
      out.write("<a href=\"login\"><font color=\"white\">로그인</font></a>");
} 
	 		else{ 
      out.write("<a href=\"logout\"><font color=\"white\">로그아웃</font></a> ");
}
      out.write(" \r\n");
      out.write("\t \t\t</p>\r\n");
      out.write("\t \t\t\r\n");
      out.write("   \t\t<p align=\"center\" style=\"text-align: center;\">\r\n");
      out.write("    \t\t<a href=\"main\">\r\n");
      out.write("    \t\t<img src=\"https://image-logo.alba.kr/data_image2/jobimg/201806/2018060321115155265_0.png\" style=\"height:100px\"/>\r\n");
      out.write("    \t\t</a>\r\n");
      out.write("    \t</p>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("\t\t<p align=\"center\" style=\"text-align: center;\"> \r\n");
      out.write("\t\t\t<a href=\"/list?cate=top\" ><font size=\"4px\">TOP</font></a> &nbsp;\r\n");
      out.write("\t\t\t<a href=\"/list?cate=bottom\"><font size=\"4px\">BOTTOM</font></a> &nbsp; \r\n");
      out.write("\t\t\t<a href=\"/list?cate=shoes\"><font size=\"4px\">SHOSE</font></a> &nbsp;\r\n");
      out.write("\t\t\t<a href=\"/list?cate=etc\"><font size=\"4px\">ETC</font></a> \r\n");
      out.write("\t\t</p>  \r\n");
      out.write("   \r\n");
      out.write("     \t\t</div>\r\n");
      out.write("  \t  \t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \t\t<div class=\"form--search\" style=\"width:200px;float:right;\"  >\r\n");
      out.write("          <input id=\"keyword\" type=\"text\" autofocus placeholder=\"Search your fassion\" onkeypress=\"if(isEnterPressed()){goCategoryPage();}\"/>\r\n");
      out.write("          <input type=\"submit\" value=\"SEARCH\" onclick=\"search(); return false\"/>\r\n");
      out.write("         <p></p>\r\n");
      out.write("         </div>\r\n");
      out.write("         <p></p>\r\n");
      out.write("\r\n");
      out.write("     </div>\r\n");
      out.write("        \r\n");
      out.write("     \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
