/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2019-08-09 00:03:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

    String result = (String)request.getAttribute("result"); //메세지값 가져오기 
    String id = (String)session.getAttribute("id");
    
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>  \r\n");
      out.write("    var result = \"");
      out.print(result);
      out.write("\"\r\n");
      out.write("    if(result==\"null\"|| result==null){} else {alert(result);}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write(" \r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("   <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Author Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources//css/main.css\" type=\"text/css\" />\r\n");
      out.write("        \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class='align'>\r\n");
      out.write("                                       \r\n");
      out.write("\r\n");
      out.write("    <div class=\"site__container site__margin\">\r\n");
      out.write("      <div class=\"grid__container\">\r\n");
      out.write("        <div style=\"text-align:center;\"><img id=\"logo-img\" style=\"width: 100%;max-height: 100%\" src=\"\" /><span style=\"color: rgb(238, 130, 238);\"><strong><span style=\"font-size: 24px;\"></span></strong></span></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"grid__container\">\r\n");
      out.write("        <form class=\"form form--search\" onSubmit=\"return false\">\r\n");
      out.write("          <input id=\"keyword\" type=\"text\" autofocus placeholder=\"Search your fassion\" onkeypress=\"if(isEnterPressed()){goCategoryPage();}\"/>\r\n");
      out.write("          <span id=\"rec-button\" class=\"rec--button\"><i class=\"fa fa-microphone\"></i></span>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"grid__container\">\r\n");
      out.write("        <form class=\"form form--search\" onSubmit=\"return false\">\r\n");
      out.write("          <div class=\"form__field\"><input type=\"submit\" value=\"SEARCH\" onclick=\"search(); return false\"/></div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <div class=\"grid__container\">\r\n");
      out.write("        <form class=\"form form--login\" action=\"login\" method=\"get\">\r\n");
      out.write("        \r\n");
      out.write("        ");
if(id==null){ 
      out.write("\r\n");
      out.write("\t<div class=\"form__field\"><input type=\"submit\" value=\"LOGIN\" onclick=\"location.href='login'; return false\" /></div>\r\n");
      out.write("\t\t");
} else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"form__field\"><input type=\"submit\" value=\"LOGOUT\" onclick=\"location.href='logout'; return false\" /></div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if("admin".equals(id)){ 
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"form__field\"><input type=\"submit\" value=\"상품업로드\" onclick=\"location.href='upload'; return false\" /></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"category__button\">\r\n");
      out.write("        <a href=\"/list?cate=top\"><img src=\"https://image-logo.alba.kr/data_image2/jobimg/201806/2018060217200649270_0.png\" alt=\"top\" ></a>\r\n");
      out.write("        <a href=\"/list?cate=bottom\"><img src=\"https://image-logo.alba.kr/data_image2/jobimg/201806/2018060217215922063_0.png\" alt=\"pants\"></a>\r\n");
      out.write("        <a href=\"/list?cate=shoes\"><img src=\"https://image-logo.alba.kr/data_image2/jobimg/201806/2018060217340466831_0.png\" alt=\"shoes\"></a>\r\n");
      out.write("        <a href=\"/list?cate=etc\"><img src=\"https://image-logo.alba.kr/data_image2/jobimg/201806/2018060217223945248_0.png\" alt=\"atc\"></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <script src=\"/resources/js/index.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("function search(){\r\n");
      out.write("\r\n");
      out.write("\tvar keyword = $(\"#keyword\").val();\r\n");
      out.write("\tlocation.href= \"search?cate=all&keyword=\"+keyword;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
