/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2019-08-09 01:05:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import gaja.project.domain.*;
import java.util.List;

public final class ProductDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("gaja.project.domain");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("    ");
  
      
    ShopVO shopdetail = (ShopVO)request.getAttribute("productdetail"); //상품리스트 가져오기
   
    String id = (String)session.getAttribute("id");
    
    String mess = (String)request.getAttribute("mess");
    
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->\r\n");
      out.write("    <title>클라우스</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"/resources/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- 메인css -->\r\n");
      out.write("    <link href=\"/resources/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->\r\n");
      out.write("    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    \r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var mess = \"");
      out.print(mess);
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("if(mess==\"null\"|| mess==null){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("} else {\r\n");
      out.write("\t\r\n");
      out.write("\talert(mess);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"padding-top:60px; background-color:#2c3338;\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function cart() {\r\n");
      out.write("\tdocument.frm1.action=\"cart\";\r\n");
      out.write("\tocument.frm1.submit();\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function shopdelete() {\r\n");
      out.write("\t\r\n");
      out.write("\tlocation.href=\"shopdelete?snum=");
      out.print(shopdetail.getSnum());
      out.write("\";\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/navi.jsp", out, false);
      out.write(" <!-- 상단바 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container-fluid\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row\">  <!-- 상품 페이지 -->\r\n");
      out.write("  \r\n");
      out.write("\t\t<form name=\"frm1\" method=\"post\" action=\"oneorder\">\r\n");
      out.write("\t\t\t<div class= \"col-md-12\" style=\"text-align:center;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class= \"col-md-1\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t<br><br><br>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class= \"col-md-10\"  style=\"text-align:center;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<P><font size=\"5%\" color=\"white\">");
      out.print(shopdetail.getSname() );
      out.write("</font> </P>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<P><font size=\"4%\" color=\"white\">판매가 : ");
      out.print(shopdetail.getPrice() );
      out.write("원</font> </P>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
String[] color = shopdetail.getColor().split(",");
String[] size = shopdetail.getSize().split(","); //콤마 기준으로 스플릿

      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table  style=\"wdith:60%;margin-left: auto; margin-right: auto;text-align:center;border: 1px solid #BDBDBD;\">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"30px\">색상 </td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"80%\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<select style=\"width:60%\" name=\"color\"> \r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i =0; i<color.length;i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(color[i]);
      out.write('"');
      out.write('>');
      out.print(color[i]);
      out.write("</option>");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"30px\">사이즈 </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select  style=\"width:60%\" name=\"size\">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i =0; i<size.length;i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(size[i]);
      out.write('"');
      out.write('>');
      out.print(size[i]);
      out.write("</option>");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"30px\">구매수량</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" value =\"1\" style=\"width:18%\" name=\"ocount\"> &nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t(잔여수량 : ");
      out.print(shopdetail.getAmount());
      out.write("개)\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("<br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form--search\" style=\"text-align:center;width:50%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(id.equals("admin")){
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"삭제하기\" style=\"width:40%;\" onclick=\"shopdelete(); return false\" />&nbsp; &nbsp;\r\n");
      out.write("  \t\t\t\t\t<input type=\"submit\" value=\"수정하기\" style=\"width:40%\" onclick=\"location.href='update?snum=");
      out.print(shopdetail.getSnum());
      out.write("'; return false\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write(" \t\t\t\t\t<input type=\"submit\" value=\"주문하기\" style=\"width:40%;\"/>&nbsp; &nbsp;\r\n");
      out.write(" \t \t\t\t\t<input type=\"submit\" value=\"장바구니\" style=\"width:40%\" onclick=\"cart(); return false\"/>\r\n");
      out.write(" \t \t\t\t\t");
}
      out.write("\r\n");
      out.write(" \t \t\t\t\t\r\n");
      out.write(" \t\t\t\t\t</div>\r\n");
      out.write(" \t\t\t\t\t\r\n");
      out.write("<br><br><br><br><br><br><hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class= \"col-md-1\" style=\"text-align:center;\"><br><br><br></div>\r\n");
      out.write("\t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class= \"col-md-12 \" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t\t\t<img src =\"");
      out.print(shopdetail.getMainimage());
      out.write("\" width=\"80%\">; <!-- 메인이미지 넣을곳 -->\r\n");
      out.write("\t\t\t\t\t\t<img src =\"");
      out.print(shopdetail.getSubimage());
      out.write("\" width=\"80%\">; <!-- 서브이미지 넣을곳 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<br><br><br><br><br><br><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<input type =\"hidden\" name =\"sname\" value=\"");
      out.print(shopdetail.getSname() );
      out.write("\">\r\n");
      out.write("<input type =\"hidden\" name =\"price\" value=\"");
      out.print(shopdetail.getPrice() );
      out.write("\">\r\n");
      out.write("<input type =\"hidden\" name =\"mainimage\" value=\"");
      out.print(shopdetail.getMainimage() );
      out.write("\">\r\n");
      out.write("<input type =\"hidden\" name =\"snum\" value=\"");
      out.print(shopdetail.getSnum());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("        <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->\r\n");
      out.write("    <script src=\"/resources/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
