/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2019-08-09 02:51:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class upload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>GAJA.shoppingmall</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/add_product.css\">\r\n");
      out.write("    <link href=\"https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#EAEAEA;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" >  \r\n");
      out.write("      <div class=\"panel panel-default\">\r\n");
      out.write("        <div class=\"panel-heading div--center\" style=\"background-color:#2c3338;\">\r\n");
      out.write("         <a href=\"main\"><img src=\"https://image-logo.alba.kr/data_image2/jobimg/201806/2018060619472176849_0.png\" alt=\"Title Image\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel-body\" style=\"background-color:#EAEAEA\">\r\n");
      out.write("          <form class=\"form-horizontal\" enctype=\"multipart/form-data\" method=\"post\" action=\"upload\">\r\n");
      out.write("            <fieldset>\r\n");
      out.write("               <!-- File Button -->\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"filebutton\">메인 제품 이미지</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                  <div id=\"image-preview-div\" class=\"div--center\" style=\"display:none;\">\r\n");
      out.write("                    <img id=\"preview-img\" class=\"preview--image\" src=\"noimage\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <input id=\"main-image\" name=\"mainimage2\" class=\"input-file\" type=\"file\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- File Button -->\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"filebutton\">상세 페이지 이미지</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                <input id=\"detail-image\" name=\"subimage2\" class=\"input-file\" type=\"file\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"product_categorie\">상품 카테고리</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                <select id=\"product_categorie\" name=\"cate\" class=\"form-control\">\r\n");
      out.write("                  <option value=\"top\">상의</option>\r\n");
      out.write("                  <option value=\"bottom\">하의</option>\r\n");
      out.write("                  <option value=\"shoes\">신발</option>\r\n");
      out.write("                  <option value=\"etc\">기타</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"product_name\">상품 이름</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                <input id=\"product_name\" name=\"sname\" placeholder=\"상품 이름\" class=\"form-control input-md\" required=\"\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"product_price\">판매가</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                <input id=\"product_price\" name=\"price\" placeholder=\"ex) 35000\" class=\"form-control input-md\" required=\"\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"product_color\">색깔</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"col-md-7\">\r\n");
      out.write("           \r\n");
      out.write("                <input type = \"text\" class=\"form-control\" id=\"color\"  value=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                     <div class=\"col-md-5\">\r\n");
      out.write("           \r\n");
      out.write("                <input type = \"button\" class=\"form-control\" onclick = \"coloradd(); return false\" value=\"색상 추가\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <input type = \"text\" class=\"form-control\" id=\"color2\" name=\"color\"   value=\"\" readonly>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"product_size\">사이즈</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-7\">\r\n");
      out.write("           \r\n");
      out.write("                <input type = \"text\" class=\"form-control\" id=\"size\"   value=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                     <div class=\"col-md-5\">\r\n");
      out.write("           \r\n");
      out.write("                <input type = \"button\" class=\"form-control\" onclick=\"sizeadd(); return false\"   value=\"사이즈 추가\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                <input type = \"text\" class=\"form-control\" id=\"size2\" name=\"size\"  value=\"\" readonly>\r\n");
      out.write("               </div>\r\n");
      out.write("                \r\n");
      out.write("                             \r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"available_quantity\">수량</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                <input id=\"available_quantity\" name=\"amount\" placeholder=\"수량\" class=\"form-control input-md\" required=\"\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-md-4 control-label\" for=\"product_description\">상세설명</label>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                <textarea class=\"form-control\" id=\"product_description\" name=\"scontent\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group div--center\">\r\n");
      out.write("                <button id=\"singlebutton\" type=\"submit\" class=\"btn-default btn-lg btn--size\" value=\"Submit Button\">등록</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn-default btn-lg btn--size\" value=\"Cancel Button\" onClick=\"history.go(-1)\"> 취소 </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </fieldset>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/js/upload-image.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function sizeadd(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar size= $(\"#size2\").val();\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    size += $(\"#size\").val()+\",\";\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    $(\"#size2\").val(size);\r\n");
      out.write("    \r\n");
      out.write("    $(\"#size\").val(\"\");\r\n");
      out.write("    \r\n");
      out.write("   \t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function coloradd(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar size= $(\"#color2\").val();\r\n");
      out.write("    size += $(\"#color\").val()+\",\";   \r\n");
      out.write("     \r\n");
      out.write("    $(\"#color2\").val(size);   \r\n");
      out.write("    $(\"#color\").val(\"\");\r\n");
      out.write("    \t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function colordelet(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
